### ISSUE TITLE
Create a first working prototype of the pdfConverter

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [UnifiedCalculation/UniCalc_pdfGenerator#2]
Create a working .jar that contains the following functionality:

- Receives JSON payload on a given port
- Parses JSON
- Creates a PDF out of the parsed data
- Returns the PDF on the given connection

The JSON payload will look something like this:

```JSON
{
   "title":"offerTitle",
   "id":1234,
   "marketBranch":"sanitär",
   "segments":[
      {
         "title":"segmentTitle",
         "articles":[
            {
               "name":"articleName",
               "id":65434,
               "unit":"m",
               "amount":15,
               "discount":7,
               "price":180,
               "description":"This is a description"
            }
         ]
      },
      {
         "title":"segmentTitle2",
         "articles":[
            {
               "name":"articleName",
               "id":651434,
               "unit":"h",
               "amount":5,
               "discount":15,
               "price":150.85,
               "description":"This is a description"
            },
            {
               "name":"articleName",
               "id":621434,
               "unit":"m",
               "amount":15,
               "discount":15,
               "price":340.45,
               "description":"This is a description"
            }
         ]
      }
   ]
}
```

The current suggestion would be using LaTeX with defined elements, then using CLI commands to parse it. 

The current langauge selection is  Java, but you're free to change to something else (for example Python to ease the usage of CLI commands).

The final application will be bundled in a Docker image, so you can assume that the needed LaTeX libraries will be installed.

**Comment by RicardoMonteiroSimoes** [comment]
According to commit c787de25a9ecf11cce0f48fd4870e342f53e7bb0 Latex doesn't seem to be a viable choice.
The next one would be to use html and generate a pdf out of it.
This library seems promising:
https://github.com/danfickle/openhtmltopdf

@deSaoJose can you try it out and report back? Also, can you create a development branch and work there, then merge finished work into master? 
There's an automatic action that runs any tests using maven on every MR

**Comment by deSaoJose** [comment]
I already implemented it using iTextpdf 7.
With the given JSON the resulting PDF looks like this at the moment:
![image](https://user-images.githubusercontent.com/61806007/77457272-bbe8be00-6dfc-11ea-9335-9635938242d5.png)

From what i can see, aslong as we don't want to do anything to fancy iTextpdf 7 should be enough. 
(@RicardoMonteiroSimoes  if this looks alright for you)
